version: '3'

volumes:
  cassandra-data:
    driver: local

services:

  cassandra:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9160:9160"
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_RPC_ADDRESS=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "8000:8000"
      - "8001:2345"
    volumes:
      - .:/clean_web
    env_file: .env

    container_name: test
    depends_on:
      - cassandra
